/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BFormGroup: typeof import('bootstrap-vue-next/components/BFormGroup')['BFormGroup']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarView: typeof import('./src/components/SidebarView.vue')['default']
    TitlebarView: typeof import('./src/components/TitlebarView.vue')['default']
  }
}
